import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export default function Home() {

  const [name, setName] = useState('')
  const [counter, setCounter] = useState(0)
  const [show, setShow] = useState(false)

  // useEffect(()  => {
  //   alert(`hello ${name}`)
  // })
  const hitung = () => {
    setCounter(counter + 1)
  }
  // const nama = (e) => {
  //   setName(e.target.value)
  // }


  return (
    <div className='h-screen'>
      <Head>
        <title>Hook React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='h-screen flex flex-col items-center justify-center'>
          {show &&
            <h1 className='text-white text-3xl font-medium' placeholder='Hi Mom!'>
              Hello {name}
            </h1>}
          <input className='border-4'
            type='text'
            key="inputan"
            onChange={e => setName(e.target.value)}
          />
          <button className=' mt-2 px-3 py-1 border rounded-md text-white'
            onClick={() => {
              setCounter(counter + 1);
              setShow(!show);
            }}>
            Increment
          </button>
          <h2 className='text-white'>
            {counter}
          </h2>
        </div>
      </main >
    </div >
  )
}
